version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:11  # Use OpenJDK 11 Docker image
    working_directory: ~/repo

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Set up Maven
          command: |
            curl -sSL https://get.sdkman.io | bash
            source ~/.sdkman/bin/sdkman-init.sh
            sdk install maven
      - run:
          name: Build with Maven
          command: mvn clean install

workflows:
  version: 2
  build:
    jobs:
      - build
